### PR TITLE
Fix NSTask race condition

### LINKED ISSUE #88: In CI/Intermittent: "The data couldn’t be read because it isn’t in the correct format"
**Description**
We are getting intermittent failures for the list command:
```
static:~ distiller$ applesimutils --list
Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.
Error: Unable to obtain a list of simulators. See “applesimutils --help” for usage.
```

**Steps to Reproduce**
Run `applesimutils --list` and it will intermittently fail

**Expected Behavior**
It should not error

**Environment**
We are on CircleCI, and this tends to happen when the machine is "busy" or has the simulator launched.
- applesimutils 0.9.4
- macOS version: 11.5.2
- Xcode version: Xcode 13.0 (13A233)

**Additional Context**
I SSHed into the circleCI machine while the tests are running. I was able to reproduce this issue intermittently with the following command:
`while applesimutils --list; do :; done`

I also attempted `while sudo applesimutils --list; do :; done` but it also failed intermittently.

If I use xcrun directly, I don't get any issues: `while xcrun simctl list --json; do :; done`

I pulled up debug logs for the process while it failed, and it gave the following: https://gist.github.com/arthuralee/f13fbdb60e75f0f91466d32d36f29ceb. It shows that the JSON from `xcrun simctl list` was fine and likely not caused by nvm/bash related issues in other similar issues (ie. #69)

I'm happy to help debug some more if you could give me some pointers. Thanks!

### LINKED ISSUE #89: In CI/Intermittent: -[NSURL initFileURLWithPath:]: nil string parameter
**Description**
I'm getting `-[NSURL initFileURLWithPath:]: nil string parameter` when running `applesimutils --list` on a CircleCI machine.
This is a relatively rare occurrence, but would still be great if tests never failed because of this. 

This is the full stack:
```
2022-02-03 17:31:56.389 applesimutils[11275:50219] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2049545f __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201cdbbb objc_exception_throw + 48
	2   Foundation                          0x00007fff210accf2 -[NSURL(NSURL) initFileURLWithPath:] + 665
	3   Foundation                          0x00007fff210ac9af +[NSURL(NSURL) fileURLWithPath:] + 83
	4   applesimutils                       0x000000010b8ee95f +[SimUtils _whichURLForBinaryName:] + 249
	5   applesimutils                       0x000000010b8eea4b __20+[SimUtils xcrunURL]_block_invoke + 28
	6   libdispatch.dylib                   0x00007fff20178806 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x00007fff2017998c _dispatch_once_callout + 20
	8   applesimutils                       0x000000010b8eea2d +[SimUtils xcrunURL] + 97
	9   applesimutils                       0x000000010b8ea9a7 main + 3102
	10  libdyld.dylib                       0x00007fff2033df3d start + 1
	11  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi: terminating with uncaught exception of type NSException
Abort trap: 6
```

Looking at the process logs, this further confirms that there is an issue when running `which xcrun`, causing `nil` to be returned.
```
2022-02-03 17:31:56.325 Db applesimutils[11275:c42b] [com.wix.applesimutils:CLI] Obtaining simulator device list
2022-02-03 17:31:56.332 Db applesimutils[11275:c42b] [com.wix.applesimutils:CLI] Running “/usr/bin/which” with argument: “xcrun”
2022-02-03 17:31:56.389 Df applesimutils[11275:c42b] (CoreFoundation) *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'
```

I doubt `/usr/bin/which` is being flaky. Perhaps there is some intermittent issue in `launchAndWaitUntilExitReturningStandardOutput`?

**Steps to Reproduce**
`applesimutils --list`

**Expected Behavior**
No crash

**Environment**
We are on CircleCI, and this tends to happen when the machine is "busy" or has the simulator launched.
- applesimutils 0.9.4
- macOS version: 11.5.2
- Xcode version: Xcode 13.0 (13A233)

### PR DESCRIPTION
**Pull request by arthuralee**
Fixes #88, fixes #89 

According to https://stackoverflow.com/questions/49184623/nstask-race-condition-with-readabilityhandler-block, there seems to be a possible race condition that causes the NSTask termination handler to fire before the data is finished being read. Additionally, there seems to be some issues with reading from `fileHandle.availableData` directly.

This PR implements the two fixes suggested by the stackoverflow post, and subsequently fixes #88 and #89 from my personal testing (I was able to reliably repro the first issue at least)

### CODE REVIEW

File: applesimutils/applesimutils/NSTask+InputOutput.m [hunk 1]
```diff
@@ -12,34 +12,51 @@ @implementation NSTask (InputOutput)
...
 	
-	dispatch_semaphore_wait(waitForTermination, DISPATCH_TIME_FOREVER);
+    // Wait twice, once for stdout and once for stderr
+	dispatch_semaphore_wait(waitForOutput, DISPATCH_TIME_FOREVER);
+    dispatch_semaphore_wait(waitForOutput, DISPATCH_TIME_FOREVER);
+    // also wait for the NSTask to terminate, otherwise we can't read terminationStatus
+    dispatch_semaphore_wait(waitForTaskTermination, DISPATCH_TIME_FOREVER);
+    
+    outPipe.fileHandleForReading.readabilityHandler = nil;
+    errPipe.fileHandleForReading.readabilityHandler = nil;
```
Comment (arthuralee) [inline applesimutils/applesimutils/NSTask+InputOutput.m:59]: I originally had these in the blocks themselves, but moved it out to avoid retain cycles. But I just saw this comment in that stackoverflow page:

>However, from testing, it looks like if you avoid -availableData and instead use -readDataOfLength in the handler block, you will eventually get a call to that block with zero-length data. If you don't nil the handler at that point, you'll get called with repeated zero-length data objects. That may be the intention, it's just not documented.

I wonder if it's worth moving these back into readabilityHandler blocks (I think we will need to create weak references to the pipes)

File: applesimutils/applesimutils/NSTask+InputOutput.m [hunk 2]
```diff
@@ -12,34 +12,51 @@ @implementation NSTask (InputOutput)
...
 	
 	NSString* stdOutStr = [[[NSString alloc] initWithData:outData encoding:NSUTF8StringEncoding] stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];
```
Comment (asafkorem) [inline applesimutils/applesimutils/NSTask+InputOutput.m:61]: Excuse my OCD, please fix the indentations (new lines are not aligned) 😅

File: applesimutils/applesimutils/NSTask+InputOutput.m (hunk 1 above)
Comment (asafkorem) [reply applesimutils/applesimutils/NSTask+InputOutput.m:59]: Then I expect the entire pipes to be released after exiting the method.

**Review by asafkorem — CHANGES_REQUESTED** [review]
@arthuralee thanks for this AMAZING contribution and the excellent investigation!
Have you verified that this solution resolves your issues?

File: applesimutils/applesimutils/NSTask+InputOutput.m (hunk 2 above)
Comment (arthuralee) [reply applesimutils/applesimutils/NSTask+InputOutput.m:61]: Ah due to my tab settings, they line up. will fix!

File: applesimutils/applesimutils/NSTask+InputOutput.m (hunk 1 above)
Comment (arthuralee) [reply applesimutils/applesimutils/NSTask+InputOutput.m:59]: Yeah that makes sense. based on the stackoverflow comment, I'm just thinking about what could go wrong if the readabilityHandler gets called multiple times with no data. Maybe I should create separate semaphores for stdout and stderr in case it gets dispatched twice?

Comment (asafkorem) [reply applesimutils/applesimutils/NSTask+InputOutput.m:59]: SGTM.

Comment (arthuralee) [reply applesimutils/applesimutils/NSTask+InputOutput.m:59]: > This makes more sense to me:
> 
> ```
> self.standardOutput = nil
> self.standardError = nil
> ```
> 
> WDYT?
> 
> Then I expect the entire pipes to be released after exiting the method.

This actually doesn't work. Apparently this method raises `NSInvalidArgumentException` once this has been set https://developer.apple.com/documentation/foundation/nstask/1407627-standardoutput?language=objc

Comment (asafkorem) [reply applesimutils/applesimutils/NSTask+InputOutput.m]: 😮

Comment (asafkorem) [reply applesimutils/applesimutils/NSTask+InputOutput.m]: So yeah, let's put the `...readabilityHandler = nil;` inside the blocks (using a weak reference) as you suggested in the first place.

Comment (asafkorem) [reply applesimutils/applesimutils/NSTask+InputOutput.m]: Especially now that we have two separated semaphores 🤔

Comment (arthuralee) [reply applesimutils/applesimutils/NSTask+InputOutput.m]: with setting the handler to nil in the block, we can make sure there are no extra calls to the handler (which makes it more technically correct), but it would not really have any effect on the outcome and the code is slightly messier. i'll leave it up to you 😄

**Comment by arthuralee** [comment]
Thanks for the quick responses! I think we might be able to close quite a few issues in this repo

**Comment by arthuralee** [comment]
Any chance we can get a new version release some time soon? 🙂
